### ISSUE TITLE
Sample slurm file for Summa Actors V3

### ISSUE THREAD

**Issue by junwei-guo** [uofs-simlab/Summa-Actors#7]
Thanks for sharing this efficient framework for the Summa users.
I have some applications using Summa V3 on the Graham cluster, Compute Canada. 
I am wondering if you can share a sample slurm file, so we can correctly allocate the computing resources for the actors model.
For example, I would like to try Summa actors on a 30-node partition (32-core per node).  
Thanks.

**Comment by KyleKlenk** [comment]
Hi Junwei, 

You can checkout this repository here: https://git.cs.usask.ca/numerical_simulations_lab/actors/paper_data/summa-actors
This contains some common script templates for Graham and Niagara for Summa, Summa-GNU-parallel, and Summa-Actors

**Comment by KyleKlenk** [comment]
Added link for sbatch scripts here: https://github.com/uofs-simlab/Summa-Actors/wiki/Supercomputer-Use

Closing this issue. Please reopen if you need additional help or the documentation is insufficient
